### ISSUE TITLE
Using defaults in code L_Shift produce "#" not "\" / How to make space hyper?

### ISSUE THREAD

**Issue by xircon** [exrok/evdoublebind#1]
Per title (On a UK keyboard.)
```
 {.key = KEY_LEFTSHIFT, .tap_key = KEY_BACKSLASH},
```
produces "#" 

You mention in your blog making spacebar into hyper, but it is not refelected in the code, how can this be done?  I use hyper a lot in emacs.

Just stumbled across this, really good work.  Used in combination with https://github.com/CZ-NIC/run-or-raise (gnome shell extension), it nearly gives me my functionality back under wayland. 

Keep up the good work :)

**Comment by exrok** [comment]
Evdoublebind inserts key codes at a low level before the keys are remapped to the keyboard layout. The key name inconsistency isn't avoidable without re-implementing a reverse key mapping translation layer as far as I am aware of. Evdoublebind just uses the `input-event-codes.h` provided by the Linux kernel headers and since these were defined with a US layout the names mostly line up but are not guaranteed to exactly correspond to specific keys in general. 

I am also working on a tool to help generate keyboard mapping which, should mitigate the problem when the tool is used for configuring. The tool should all be able to generate the external key mapping for XKBlayout which may help with your second issue discussed below.

### Hyper key
The current version, can only add additional key-presses. Essentially if I wanted spacebar as hyper I would first need to configure the keyboard layout to map spacebar to hyper (currently on  wayland the only way I know how to do that is by "modifying the system XKB database in `/usr/share/X11/xkb`" see [issue](https://unix.stackexchange.com/a/355428). Of course, now the space bar would only be hyper but that's where evdoublebind comes in; I would configured to insert `KEY_F13`, a key not present on my keyboard, when the space bar is tapped shown below.
```c++
{.key = KEY_SPACE,     .tap_key = KEY_F13},
```
Then in the my keyboard layout I remap `KEY_F13` to space restoring the functionally.  I think the most confusing is part is that if you are only adding simple functionally to a key that is already a modifier it's simple. As the modifier key retains all of it's normal functionally except when tapped which Evdoublebind can just insert. However if your converting a normal key to a modifier key then evdoublebind does not handle the case in which the key is held and a modification in the keyboard layout mapping is needed.

Further, in my blog post, I showed how I modified my keyboard layout mapping via Xmodmap, however this only works on X11 since I haven't quite settled on solution for Wayland; modifying the system XKB database seems really hacky to me.

Edit: Soon, if not already, XKB modification will be able to be put in ~/.xkb` to perform the translation on wayland, see issues [...wildcard parsing...](https://github.com/xkbcommon/libxkbcommon/issues/99) and [Pluggable Layout Support](https://github.com/xkbcommon/libxkbcommon/issues/40).

**Comment by xircon** [comment]
Thanks, understand a bit better.  I have posted about evdoublebind on the Manjaro forum and on the Emacs reddit, really excellent program.

**Comment by exrok** [comment]
I am still working on writing up an easier configuration guide but I have now got something working on wayland, sway. 

Xkb config in `~/.xkb/symbols/custom`
```
xkb_symbols "evdoublebind" {
    replace key <AC10> { [ Super_L ]  }; //semicolon
    replace key <FK14> { [ semicolon, colon ]  }; //restore semicolon
    replace key <FK13> { [ space ]  }; //restore space
    replace key <SPCE> { [ Control_L ]  };
    replace key <CAPS> { [ Hyper_L ] };
    modifier_map Mod3 { <CAPS> };
    modifier_map Control { Control_L, Control_R, <SPCE> };
    modifier_map Mod4 { Super_L, Super_R, <AC10> };
};
```
And then tell sway to use via it's config. Still working on the exact details as currently it is just an exact translation of my Xmodmap. Exact config setup is still work in progress.

**Comment by exrok** [comment]
Evdoublebind now has a new configuration system which can handle XKB key translation and generates the XKB configuration files for you. 

Depending on how you have configured you keyboard layout you may need to specify it explicitly like so,
`evdoublebind-inspector -l gb` and `evdoublebind-make-config -l gb config.conf`.

In the new configuration, `<LFSH> : Shift_L   | backslash`, should now produce the correct results on different keyboard layouts.

The XKB configuration generated by `evdoublebind-make-config` is easy to use on i3wm and sway but in other environments your mileage may vary. After some quick searching around for adjusting the XKB settings on Gnome, I think something like this,
```sh
gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'gb')]"
gsettings set org.gnome.desktop.input-sources xkb-rules "['evdev-doublebind']"
gsettings set org.gnome.desktop.input-sources xkb-options "['evdoublebind:mapping']"
```
might work.

I have updated the README and written a [post](https://i64.dev/low-level-keyboards-hacks-easy-to-use/) detailing usage and the improvements made.

**Comment by xircon** [comment]
I ended up with:
```c
// Some entrys remain unchanged from your original sample file:
const KeyBind KEYMAP[] = {
     {.key = KEY_LEFTSHIFT, .tap_key = KEY_BACKSPACE, KEY_ESC},
     {.key = KEY_RIGHTSHIFT,.tap_key = KEY_D, .tap_modifier = KEY_LEFTMETA},
     {.key = KEY_LEFTCTRL,  .tap_key = KEY_T, .tap_modifier = KEY_LEFTMETA},
     {.key = KEY_RIGHTCTRL,  .tap_key = KEY_J, .tap_modifier = KEY_LEFTMETA},
     {.key = KEY_SEMICOLON, .tap_key = KEY_F14},
     {.key = KEY_LEFTALT,   .tap_key = KEY_W, .tap_modifier = KEY_LEFTMETA},
     {.key = KEY_CAPSLOCK,  .tap_key = KEY_E, .tap_modifier = KEY_LEFTMETA},
     {.key = KEY_LEFTMETA,  .tap_key = KEY_F1, .tap_modifier = KEY_LEFTALT}
 };
```
Replicating the behaviour I had with xcape e.g.:
Tap Caps generates a "super+e" which is defined in Plasma as emacs.
Tap Left Alt generated "super+w" ditto as firefox.
and so on.

I am still reading and getting my head around all the changes you have made.  But I cannot see a way in the new method to tap and send a chorded keystroke? 

The other problem is the mod of a key, in xmodmap I used:
```
! Unmap capslock
clear Lock
keycode 135 = End
keycode 108 = Home
!keycode 108 = Hyper_L

! Leave mod4 as windows key _only_
remove mod4 = Hyper_L

add mod3 = Hyper_L

keycode 65 = Hyper_L
keycode any = space
```
Moving hyper to mod3.  The problem in Gnome is I cannot see an obvious way to move the mod from 4 to 3.

But as I said, it is a lot to absorb, so will reread tomorrow as it is late here (UK).

**Comment by exrok** [comment]
Edit: Address chorded keystroke.

I did remove the ability to "tap and send a chorded keystroke", if you referring to the tap_modifier, as for my use case it was just a work around that the new config system fixes.

This snippet from your config was using ESC as modifier, holding it down then pressing backspace.
``` {.key = KEY_LEFTSHIFT, .tap_key = KEY_BACKSPACE, KEY_ESC}```

However, now seeing how you use the, tap modifier, feature to interact with preexisting key bindings in other applications, I am going to add it back.

But before I do that, I have installed Gnome and I am going to try in figure out a solution for configuring XKB.

**Comment by exrok** [comment]
I got it working on gnome, both X11 and wayland. However, it requires modifying system files, namely `/usr/share/X11/xkb/rules/evdev` to add the custom option, further the option is added to `/usr/share/X11/xkb/symbols/`. This requirement is caused by a limitation in gnome as it neither reads the  user XKB directory nor allows setting a custom rule. 

If your using Arch Linux the use of a Pacman install hook can automate the insertion of the custom rule. Further, the added file to `/usr/share/X11/xkb/symbols/` should not conflict and thus not be modified or removed during updates. Therefore, if care is taken, modifying the required system files should be safe.

 I will write an exact guide soon but first I will add tap key modifiers back so I can write the guide aimed at your config.

**Comment by exrok** [comment]
I have add back tap modifiers and modified the config system to accommodate the new capabilities.

I have pushed a Work In Progress [guide for gnome aim at arch linux](https://github.com/exrok/evdoublebind/blob/master/guides/gnome.md) . The guide is missing some important parts ATM but does introduce and describe how to use the newly reintroduce direct bindings.
