### ISSUE TITLE
Support for Wayland

### ISSUE THREAD

**Issue by jbriales** [exrok/evdoublebind#2]
This is an *awesome* work, which seems *awesomely* documented (unlike many things around keyboard mapping land) :)
I did a similar work for mapping CapsLock myself in the past (https://github.com/jbriales/xkb-extended-keys) but that's strongly based on XKB and doesn't work on Wayland.

Cutting to the chase: What's the current status of Wayland support for this solution? :)

**Comment by exrok** [comment]
I am currently using evdoublebind with sway (wayland) and I got it working on Gnome using wayland  (WIP guide: https://github.com/exrok/evdoublebind/blob/master/guides/gnome.md ). All wayland environments that I am aware of actually still uses XKB for process/mapping keyboard. Further, I not aware of any work to move away from using XKB for wayland environments.

I intend to update/finish wayland documentation soon (along with add a couple more settings to the configuration system)

Some like desktop environments like Gnome don't let you specify custom XKB rules directly so you have to resort modifying the system XKB rules as I showed in the guide. This may have changes since I have not tried on Gnome in months.

I haven't tried but xkb-extended-keys should work with most wayland compositors if you where to modify the system level definitions which for me is in `/usr/share/X11/xkb/` for both wayland and X11.  

For sway when I am using evdoublebind I place the config in `~/.xkb/symbols/evdoublebind` and then configure sway to use it with in the config.
```
input '*' xkb_rules evdev-doublebind
input '*' xkb_options evdoublebind:mapping
```
This script is basically the  setup for sway https://github.com/exrok/evdoublebind/blob/master/examples/sway_example.sh

**Comment by jbriales** [comment]
That answers the question fantastically. Thanks!
